version: "3.7"

services:
    nginx:
        build:
            context: docker
            dockerfile: development/nginx/Dockerfile
        volumes:
            - ./api:/app
        depends_on:
            - api-php-fpm
        ports:
            - "8088:80"
    api-php-fpm:
        build:
            context: docker
            dockerfile: development/php-fpm/Dockerfile
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            PHP_IDE_CONFIG: serverName=API
        volumes:
            - ./api:/app