services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Domain\Sender\SenderInterface:
            tags:
                - { name: api.sender }

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'


    App\Api\Controller\v1\NotificationController:
        public: true
        arguments:
            $senders: !tagged_iterator api.sender
